name: 'Setup Swagger Codegen'
description: 'Sets up swagger-codegen and erlang-generator'

inputs:
  codegen-version:
    description: 'Codegen (swagger-api/swagger-codegen) version to use.'
    required: true
    type: string
  generator-version:
    description: 'Erlang generator (valitydev/swagger-generator-erlang) version to use.'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Check Java
      run: java --version

    - name: Download swagger-codegen
      run: |
        wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/${{ inputs.codegen-version }}/swagger-codegen-cli-${{ inputs.codegen-version }}.jar -O /usr/local/lib/swagger-codegen/swagger-codegen-cli.jar

    # - name: Download swagger-generator-erlang
    #   run: |
    #     wget someurl -O /usr/local/lib/swagger-codegen/swagger-generator-erlang.jar

    - name: Make swagger-codegen shortcut
      run: |
        echo "#!/bin/sh" > /usr/local/bin/swagger-codegen
        echo "java -cp /usr/local/lib/swagger-codegen/swagger-codegen-cli.jar io.swagger.codegen.SwaggerCodegen \$*" >> /usr/local/bin/swagger-codegen
        chmod +x /usr/local/bin/swagger-codegen

    - name: Test codegen
      run: |
        /usr/local/bin/swagger-codegen version
        /usr/local/bin/swagger-codegen langs
